namespace ArmenianAiToy.Domain.Entities;

/// <summary>
/// One piece of content the OWNER added from the console, rather than a
/// developer added to <c>ContentSync</c> config and shipped in the container
/// image.
///
/// <para>
/// <b>Two content roots, permanently.</b> A config row's audio lives in git
/// under <c>ContentSync:AudioRoot</c> (<c>story-audio/</c>, inside the image);
/// a row of THIS table's audio lives on the persistent volume under
/// <c>ContentSync:UploadRoot</c> (<c>/data/content-uploads</c> in the Railway
/// layout, the exact precedent of <c>Audio:BlobStoreRoot</c>). The rule is
/// absolute and there is no mixed mode: <b>config rows always resolve under
/// AudioRoot, DB rows always under UploadRoot.</b> Migrating the shipped
/// catalogue onto the volume would break two keystone tests, three csproj
/// globs and the shipper's placeholder discipline for no user-visible gain.
/// </para>
///
/// <para>
/// <b><see cref="DefaultEnabled"/> = false means FLEET-DARK.</b> The item is
/// absent from every toy's manifest and reaches a toy only through an explicit
/// <c>allow</c> row in <c>DeviceContentOverrides</c> — which is precisely
/// "send this new story to the bench toy first". Flipping it true is "release
/// it to the fleet". That is why this table carries a default and the override
/// table carries the exceptions, rather than a second entitlement mechanism.
/// </para>
///
/// <para>
/// <b>Delete is a soft retire</b> (<see cref="RetiredAt"/>): the item leaves
/// every manifest immediately, but the toy's carry-forward keeps the file on
/// its card until a later sweep reclaims it. A child should not lose a story
/// mid-listen because an adult pressed a button in a console.
/// </para>
///
/// <para>
/// <b><see cref="RelativePath"/> is generated by the server</b>
/// (<c>&lt;itemKey&gt;-v&lt;N&gt;.mp3</c>), never derived from the uploaded
/// filename or any other operator input. That preserves the invariant the
/// whole content-sync contract rests on — an id is a lookup key that never
/// reaches the filesystem — on the one path in this repo that actually writes
/// a file an operator chose.
/// </para>
///
/// <para>
/// No FK to anything: the catalogue is fleet-level, not device-level. The
/// per-device relationship lives in <c>DeviceContentOverride</c>, which is
/// keyed by the same <see cref="ItemKey"/> this row uses, so entitlement and
/// delivery can never disagree about what "this item" means.
/// </para>
/// </summary>
public class ContentItem
{
    public Guid Id { get; set; }

    /// <summary>Which namespace the item lives in: <c>story</c> |
    /// <c>game</c> | <c>voice</c> | <c>music</c>, the same four
    /// <c>DeviceContentEntitlement.Kinds</c> the override table uses.
    /// <para>
    /// Only <c>story</c> can be written today — the upload endpoint is
    /// <c>POST /api/internal/content/stories</c> and there is no other writer.
    /// The column is bounded to the four from the start so a later
    /// game/voice/music upload is an endpoint, not a migration.
    /// </para></summary>
    public string Kind { get; set; } = string.Empty;

    /// <summary>The item's address within its namespace — a story id, a track
    /// id, a voice clip id, or <c>gameKey/clipId</c> for a game. Held to the
    /// SAME allowlist the manifest holds every content id to (lowercase ASCII,
    /// digits, <c>-</c>, <c>_</c>, bounded at 48) because it becomes a
    /// component of the generated filename AND of the SD filename on the
    /// toy.</summary>
    public string ItemKey { get; set; } = string.Empty;

    /// <summary>Display title. Informational on the device (it only logs it);
    /// it is what the parent library and the console show.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Content version. Bumped on every re-upload of the same
    /// <see cref="ItemKey"/>, because a toy that already holds the story keeps
    /// its cached copy otherwise — the failure this repo has already shipped
    /// twice with the hand-run shipper.</summary>
    public int Version { get; set; } = 1;

    /// <summary>Server-generated filename relative to
    /// <c>ContentSync:UploadRoot</c>. Never absolute, never operator-supplied;
    /// re-validated on the way back out so a hand-edited row still cannot
    /// escape the upload root.</summary>
    public string RelativePath { get; set; } = string.Empty;

    /// <summary>Lowercase hex SHA-256 of the file, computed BY THE SERVER
    /// while the upload streamed. This is what retires the hand-run
    /// <c>Ship-StoryAudio.ps1</c> ritual and the hand-added placeholder
    /// config row.</summary>
    public string Sha256 { get; set; } = string.Empty;

    /// <summary>Exact byte length, measured by the server for the same
    /// reason.</summary>
    public long SizeBytes { get; set; }

    /// <summary>False = fleet-dark (reachable only via an explicit per-device
    /// <c>allow</c>). Uploads land false, on purpose: nothing an owner uploads
    /// reaches a child's toy until he has heard it on one toy and said so.</summary>
    public bool DefaultEnabled { get; set; }

    /// <summary>Soft delete. Non-null → the item is in no manifest. The file
    /// is deliberately left on disk and on every card.</summary>
    public DateTime? RetiredAt { get; set; }

    /// <summary>The resolved console operator name, so a row is traceable to
    /// a person without joining the audit feed — same field and same reason as
    /// <c>DeviceContentOverride.CreatedBy</c>.</summary>
    public string CreatedBy { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; }
}
