namespace ArmenianAiToy.Application.Helpers;

/// <summary>
/// The ONE function that turns the config catalogue plus the owner's uploaded
/// <c>ContentItem</c> rows into one catalogue.
///
/// <para>
/// It sits UNDER <see cref="DeviceContentEntitlement"/>, not beside it, and the
/// order matters: this adds what the catalogue contains, then that removes what
/// a particular toy is denied. Two layers, each with one job, so "why is this
/// story not on that toy" has exactly two places to look.
/// </para>
///
/// <para>
/// <b>Config rows resolve under <c>AudioRoot</c>, DB rows under
/// <c>UploadRoot</c>.</b> That is the whole reason this is a separate step: a
/// DB row's path is made ABSOLUTE here, before it joins a list whose remaining
/// members were resolved against a different root. Once every path in the list
/// is absolute, <c>ResolveAudioPath</c> is a no-op on all of them and no later
/// caller has to know where an item came from.
/// </para>
///
/// <para>
/// <b>No uploaded items means the SAME OBJECT back</b>, the invariant
/// <see cref="DeviceContentEntitlement.Apply"/> established: a deployment that
/// has never uploaded anything gets the DI singleton by reference, so its
/// manifest is byte-identical to the day before this shipped rather than merely
/// equal-looking.
/// </para>
///
/// <para>
/// Pure: no DB, no IO, no config reads, no clock. Filtering by
/// <c>DefaultEnabled</c> / <c>RetiredAt</c> is the CALLER's job, because only
/// the caller knows whether it is building the fleet catalogue or one toy's.
/// </para>
/// </summary>
public static class ContentItemOverlay
{
    /// <summary>The flat projection of a <c>ContentItem</c> row this helper
    /// needs. A record rather than the entity so the helper stays pure and
    /// testable without a DbContext, matching the tuple seam
    /// <see cref="DeviceContentEntitlement.Apply"/> uses.</summary>
    public readonly record struct Item(
        string Kind,
        string Key,
        string Title,
        int Version,
        string RelativePath,
        string Sha256,
        long SizeBytes);

    /// <summary>
    /// The configured upload root as an absolute directory, or false when none
    /// is configured. A relative root resolves against the app base directory,
    /// exactly as <c>ContentSyncOptions.ResolveAudioPath</c> treats
    /// <c>AudioRoot</c> — so a bench can point at a folder beside the binary
    /// while production points at the volume, with no code difference.
    /// <para>
    /// The one resolution site, shared by the read path (below) and the upload
    /// endpoint, so a file can never be WRITTEN somewhere the manifest will not
    /// look for it.
    /// </para>
    /// </summary>
    public static bool TryResolveRoot(string? uploadRoot, out string absoluteRoot)
    {
        absoluteRoot = string.Empty;
        if (string.IsNullOrWhiteSpace(uploadRoot))
        {
            return false;
        }
        absoluteRoot = Path.IsPathRooted(uploadRoot)
            ? Path.GetFullPath(uploadRoot)
            : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, uploadRoot));
        return true;
    }

    /// <summary>
    /// Resolves an uploaded item's server-generated relative path against the
    /// upload root, and refuses anything that does not land INSIDE it.
    ///
    /// <para>
    /// The path is generated by the server and validated at the upload
    /// endpoint, so nothing today can reach this with a traversal. It is
    /// checked anyway because this is the one place in the content pipeline
    /// where a value that came off a wire ends up as a filesystem path, and a
    /// hand-edited row, a restored backup, or a future second writer must not
    /// be able to turn the device content-file endpoint into an arbitrary file
    /// reader.
    /// </para>
    ///
    /// <para>
    /// An unset <paramref name="uploadRoot"/> fails here rather than later:
    /// the alternative is a manifest that advertises a story every toy then
    /// fails to download, which is the exact fleet-wide
    /// <c>download_failed</c> trap this slice exists to avoid.
    /// </para>
    /// </summary>
    public static bool TryResolveUploadPath(
        string? uploadRoot, string? relativePath, out string absolutePath)
    {
        absolutePath = string.Empty;
        if (!TryResolveRoot(uploadRoot, out var root)
            || string.IsNullOrWhiteSpace(relativePath))
        {
            return false;
        }
        // An absolute stored path would bypass the containment check below by
        // construction — ResolveAudioPath returns a rooted path untouched — so
        // it is refused outright. The server only ever stores a bare filename.
        if (Path.IsPathRooted(relativePath))
        {
            return false;
        }

        var resolved = Path.GetFullPath(Path.Combine(root, relativePath));

        // Containment, compared with a trailing separator so "/data/uploads-evil"
        // is not read as being inside "/data/uploads".
        var rootWithSeparator = root.EndsWith(Path.DirectorySeparatorChar)
            ? root
            : root + Path.DirectorySeparatorChar;
        if (!resolved.StartsWith(rootWithSeparator, StringComparison.Ordinal))
        {
            return false;
        }

        absolutePath = resolved;
        return true;
    }

    /// <summary>
    /// The catalogue <paramref name="baseline"/> with <paramref name="items"/>
    /// added.
    /// </summary>
    /// <param name="baseline">The config catalogue (the DI singleton).</param>
    /// <param name="items">The uploaded rows the caller has already decided
    /// belong in this catalogue — non-retired, and either fleet-enabled or
    /// explicitly allowed on the device being resolved. Empty / null returns
    /// <paramref name="baseline"/> itself.</param>
    public static ContentSyncOptions Apply(
        ContentSyncOptions baseline, IEnumerable<Item>? items)
    {
        ArgumentNullException.ThrowIfNull(baseline);
        if (items is null)
        {
            return baseline;
        }

        // Config wins a key collision, and the endpoint refuses to create one,
        // so this is belt and braces: a shipped story can never be shadowed by
        // an upload that happens to reuse its id.
        var configStories = baseline.ResolveStories();
        var takenStoryKeys = configStories
            .Where(s => !string.IsNullOrWhiteSpace(s.StoryId))
            .Select(s => s.StoryId.Trim())
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var uploadedStories = new List<ContentSyncStoryOptions>();
        foreach (var item in items)
        {
            // Only `story` is writable today (the sole endpoint is
            // /content/stories), so anything else is unreachable rather than
            // silently dropped. A game/voice/music upload adds its branch here
            // together with its endpoint.
            if (!string.Equals(
                    DeviceContentEntitlement.NormalizeKind(item.Kind),
                    DeviceContentEntitlement.KindStory, StringComparison.Ordinal))
            {
                continue;
            }

            var key = DeviceContentEntitlement.NormalizeKey(item.Key);
            if (key.Length == 0 || !takenStoryKeys.Add(key))
            {
                continue;
            }
            if (!TryResolveUploadPath(baseline.UploadRoot, item.RelativePath, out var absolute))
            {
                continue;
            }

            uploadedStories.Add(new ContentSyncStoryOptions
            {
                StoryId = key,
                Version = item.Version < 1 ? 1 : item.Version,
                Title = item.Title ?? string.Empty,
                // Left empty on purpose: the manifest service fills in this
                // backend's own device-authed streamer scoped to this story,
                // which is the only URL that can serve a file living outside
                // the image.
                AudioUrl = string.Empty,
                AudioPath = absolute,
                Sha256 = item.Sha256 ?? string.Empty,
                SizeBytes = item.SizeBytes,
            });
        }

        if (uploadedStories.Count == 0)
        {
            return baseline;
        }

        // Same construction as DeviceContentEntitlement.Apply, and for the same
        // reasons: the lists are already RESOLVED (so AudioRoot is blanked and
        // every path is absolute), and the legacy scalars stay at their
        // defaults because the Stories list is authoritative from here on.
        return new ContentSyncOptions
        {
            Enabled = baseline.Enabled,
            AudioRoot = string.Empty,
            UploadRoot = baseline.UploadRoot,
            Stories = configStories.Concat(uploadedStories).ToList(),
            Games = baseline.ResolveGames().ToList(),
            Voice = baseline.ResolveVoice().ToList(),
            Music = baseline.ResolveMusic().ToList(),
        };
    }
}
