#!/usr/bin/env bash
# -------------------------------------------------------------
# render_canned_clip.sh
#
# Renders the one Armenian failure clip the firmware plays on
# any error path, and rewrites canned_clip.h as a PROGMEM byte
# array. Uses the same TTS provider + voice the backend uses
# (OpenAI tts-1 / Nova) so the voice identity is consistent
# with Areg's normal response audio.
#
# Requirements:
#   - curl
#   - xxd (bundled with vim on macOS / most Linux distros)
#   - OPENAI_API_KEY in env
#
# Usage (from esp32/AregVoiceMvp/):
#   export OPENAI_API_KEY=sk-...
#   ./tools/render_canned_clip.sh
# -------------------------------------------------------------
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT_MP3="$HERE/canned_clip.mp3"
OUT_HEADER="$HERE/canned_clip.h"
# «Հիմա չեմ լսում քեզ, մի քիչ հետո կրկին փորձի՛ր։»
TEXT='Հիմա չեմ լսում քեզ, մի քիչ հետո կրկին փորձի՛ր։'

if [ -z "${OPENAI_API_KEY:-}" ]; then
    echo "error: OPENAI_API_KEY not set" >&2
    exit 1
fi
if ! command -v xxd >/dev/null 2>&1; then
    echo "error: xxd not found. Install vim / xxd." >&2
    exit 1
fi

echo "[render] calling OpenAI TTS (tts-1 / Nova) ..."
curl -sS -X POST "https://api.openai.com/v1/audio/speech" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"model\":\"tts-1\",\"voice\":\"nova\",\"input\":\"$TEXT\"}" \
    -o "$OUT_MP3"

if [ ! -s "$OUT_MP3" ]; then
    echo "error: TTS returned empty body" >&2
    exit 1
fi
BYTES=$(wc -c < "$OUT_MP3")
echo "[render] wrote $OUT_MP3 ($BYTES bytes)"

# Regenerate canned_clip.h. xxd -i outputs a C array named
# from the file; we munge it to match the canned_clip_mp3
# / canned_clip_mp3_len names the firmware references.
TMP_HDR="$(mktemp)"
trap 'rm -f "$TMP_HDR"' EXIT
cat > "$TMP_HDR" <<'HEADER'
// -------------------------------------------------------------
// AregVoiceMvp / canned_clip.h
// GENERATED by tools/render_canned_clip.sh — do not edit by hand.
// Regenerate when the failure-clip copy or voice provider changes.
// -------------------------------------------------------------
#pragma once

#include <Arduino.h>
#include <pgmspace.h>

static const uint8_t canned_clip_mp3[] PROGMEM = {
HEADER
# xxd -i emits both the array body and a _len; we skip the
# generated header/footer and take only the hex-byte middle.
xxd -i "$OUT_MP3" | sed -n '/^[[:space:]]*0x/p' >> "$TMP_HDR"
cat >> "$TMP_HDR" <<HEADER
};

static const size_t canned_clip_mp3_len = sizeof(canned_clip_mp3);
HEADER

mv "$TMP_HDR" "$OUT_HEADER"
trap - EXIT
echo "[render] rewrote $OUT_HEADER"
echo "[render] done — rebuild the sketch and reflash."
