#!/usr/bin/env bash
# Builds an installable Android release APK for the Areg parent app locally —
# no EAS account, no cloud build queue. Signs with a THROWAWAY keystore
# generated on the fly (see the big warning below). Never commit the APK or
# the keystore; both land under android/, which .gitignore already excludes
# wholesale, and this script also removes the keystore's passphrase file
# after use.
#
# Requires, NOT installed by this script:
#   - Node 20+ and npm (same as running the app any other way)
#   - JDK 17 (what Android Gradle Plugin documents; this project's Gradle/AGP
#     combo has also been exercised against JDK 21 — see README "Android
#     build" section for what was actually verified in CI/dev containers)
#   - Android SDK command-line tools, with ANDROID_HOME (or
#     ANDROID_SDK_ROOT) pointing at them, platform-tools, the platform
#     matching this project's compileSdkVersion, and a matching build-tools
#     version installed via `sdkmanager`. This script does NOT fetch the
#     SDK — some networks block dl.google.com entirely, and guessing at a
#     silent auto-install is worse than a clear early failure.
#
# What it does, in order:
#   1. `npx expo prebuild --platform android --clean` — regenerates ./android
#      from app.json (gitignored; safe to delete and regenerate any time).
#   2. Generates a throwaway upload keystore at
#      android/app/areg-throwaway-release.keystore if one is not already
#      there (pass --fresh-keystore to force a new one).
#   3. Patches the generated android/app/build.gradle so the `release`
#      build type signs with that keystore instead of the debug key Expo
#      wires up by default (patch step, not a hand-edit — android/ is
#      regenerated by step 1 on every run).
#   4. Runs `./gradlew assembleRelease`.
#   5. Prints the resulting .apk path and its size.
#
# Usage:
#   cd mobile/AregParent
#   ANDROID_HOME=/path/to/sdk ./scripts/build-android.sh
#   ./scripts/build-android.sh --fresh-keystore   # rotate the throwaway key
#
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"

FRESH_KEYSTORE=0
for arg in "$@"; do
  case "$arg" in
    --fresh-keystore) FRESH_KEYSTORE=1 ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# 0. Preflight
# ---------------------------------------------------------------------------
: "${ANDROID_HOME:=${ANDROID_SDK_ROOT:-}}"
if [ -z "${ANDROID_HOME}" ]; then
  cat >&2 <<'EOF'
error: ANDROID_HOME (or ANDROID_SDK_ROOT) is not set.

This script does not download the Android SDK. Install the command-line
tools yourself (https://developer.android.com/studio#command-tools), then
install at least platform-tools plus the platform/build-tools this Expo SDK
targets (the first `./gradlew` run below will name the exact missing
platform/build-tools version if you guess wrong — accept it and re-run
sdkmanager with that exact string), e.g.:

  export ANDROID_HOME=/path/to/sdk
  yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" \
      "platform-tools" "platforms;android-<N>" "build-tools;<N>.0.0"

and re-run this script. (In a network-restricted environment, dl.google.com
may be blocked outright — that is a policy decision outside this script's
control, not a bug in it; this exact block was hit and documented in
mobile/AregParent/README.md's "Android build" section.)
EOF
  exit 1
fi
if [ ! -d "$ANDROID_HOME" ]; then
  echo "error: ANDROID_HOME=$ANDROID_HOME does not exist." >&2
  exit 1
fi

command -v keytool >/dev/null 2>&1 || { echo "error: keytool not found — install a JDK (17 recommended)." >&2; exit 1; }
command -v npx >/dev/null 2>&1 || { echo "error: npx not found — install Node." >&2; exit 1; }

# ---------------------------------------------------------------------------
# 1. Regenerate the native Android project from app.json
# ---------------------------------------------------------------------------
echo "==> expo prebuild --platform android"
CI=1 npx expo prebuild --platform android --clean

BUILD_GRADLE="android/app/build.gradle"
[ -f "$BUILD_GRADLE" ] || { echo "error: $BUILD_GRADLE not found after prebuild." >&2; exit 1; }

# ---------------------------------------------------------------------------
# 2. Throwaway keystore
# ---------------------------------------------------------------------------
KEYSTORE="android/app/areg-throwaway-release.keystore"
KEY_ALIAS="areg-throwaway"
# Fixed, published-in-this-script passphrase — THIS IS THE POINT. A real
# release key's passphrase must never appear in a repo; this one is
# deliberately public because the keystore itself is regenerated locally,
# gitignored, and not the key any real release ships with (see README).
KEY_PASS="areg-throwaway-pass"

if [ "$FRESH_KEYSTORE" = "1" ] && [ -f "$KEYSTORE" ]; then
  rm -f "$KEYSTORE"
fi

if [ ! -f "$KEYSTORE" ]; then
  echo "==> generating a THROWAWAY keystore (not for a real release — see README)"
  keytool -genkeypair -v \
    -keystore "$KEYSTORE" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 3650 \
    -storepass "$KEY_PASS" -keypass "$KEY_PASS" \
    -dname "CN=Areg Parent (throwaway dev build), OU=dev, O=dev, L=dev, ST=dev, C=US"
else
  echo "==> reusing existing throwaway keystore at $KEYSTORE (--fresh-keystore to rotate)"
fi

# ---------------------------------------------------------------------------
# 3. Wire the throwaway keystore into the release build type
# ---------------------------------------------------------------------------
# expo prebuild always regenerates build.gradle with a `release` build type
# signed by signingConfigs.debug (see the comment it leaves: "Caution! In
# production, you need to generate your own keystore file."). Patch that in
# place, every run — android/ is disposable, so this is idempotent by
# construction rather than a one-time hand-edit that prebuild would erase.
python3 - "$BUILD_GRADLE" "$KEY_ALIAS" "$KEY_PASS" <<'PYEOF'
import re, sys
path, alias, pw = sys.argv[1], sys.argv[2], sys.argv[3]
src = open(path).read()

release_signing_config = f'''        release {{
            storeFile file('areg-throwaway-release.keystore')
            storePassword '{pw}'
            keyAlias '{alias}'
            keyPassword '{pw}'
        }}
    }}'''

# Insert a `release` signingConfigs block right after the `debug` one closes.
pattern = re.compile(r"(signingConfigs\s*\{\s*debug\s*\{[^}]*\}\n)(\s*\})", re.S)
if "signingConfigs.release" not in src:
    src, n = pattern.subn(lambda m: m.group(1) + release_signing_config, src, count=1)
    if n != 1:
        sys.exit("error: could not find signingConfigs { debug { ... } } block to patch")

# Point the release build type at the new signing config instead of debug's.
src = src.replace(
    "release {\n            // Caution! In production, you need to generate your own keystore file.\n            // see https://reactnative.dev/docs/signed-apk-android.\n            signingConfig signingConfigs.debug",
    "release {\n            // Throwaway signing wired by scripts/build-android.sh — see mobile/AregParent/README.md.\n            signingConfig signingConfigs.release",
)

open(path, "w").write(src)
PYEOF

if ! grep -q "signingConfigs.release" "$BUILD_GRADLE"; then
  echo "error: failed to wire the throwaway keystore into $BUILD_GRADLE (release signingConfig still points at debug)." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 4. Build
# ---------------------------------------------------------------------------
echo "==> ./gradlew assembleRelease"
cd android
chmod +x ./gradlew
./gradlew assembleRelease --console=plain
cd "$APP_DIR"

# ---------------------------------------------------------------------------
# 5. Report
# ---------------------------------------------------------------------------
APK="android/app/build/outputs/apk/release/app-release.apk"
if [ -f "$APK" ]; then
  SIZE_BYTES=$(stat -c%s "$APK" 2>/dev/null || stat -f%z "$APK")
  SIZE_MB=$(awk -v b="$SIZE_BYTES" 'BEGIN{printf "%.1f", b/1024/1024}')
  echo "==> Built: $APK (${SIZE_MB} MB)"
  echo "    Install on a phone with USB debugging: adb install -r \"$APK\""
else
  echo "error: expected APK not found at $APK — check the Gradle output above." >&2
  exit 1
fi
